import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { Header } from "@/components/header/Header";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex bg-[#f7f9fd] h-[100vh] overflow-y-hidden">
          <Navbar />
          <div className="flex-grow">
            <Header />
            {children}
          </div>
        </main>
        <Toaster/>
      </body>
    </html>
  );
}
